version: 2
jobs:
  test-py27:
    docker:
      - image: continuumio/miniconda
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: patch distro
          command: sudo apt-get update && sudo apt-get install -y build-essential wget unzip git cmake python3 python-dev python3-dev libssl-dev && sudo apt-get clean && sudo apt-get purge -y

      - run:
          name: patch cmake
          command: cd /tmp && sudo wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz && sudo tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz && sudo cp -R cmake-3.3.2-Linux-x86_64/bin /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/doc /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/man /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/share /usr/

      - run:
          name: install dependencies
          command: sudo pip install -e '.[develop]'

      - run:
          name: run tests
          command: py.test --cov=genomelake tests/

      - run:
          name: run coveralls
          command: coveralls || true

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-py35:
    docker:
        # TODO check
      - image: circleci/python:3.5


    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: patch distro
          command: sudo apt-get update && sudo apt-get install -y build-essential wget unzip git cmake python3 python-dev python3-dev libssl-dev && sudo apt-get clean && sudo apt-get purge -y

      - run:
          name: patch cmake
          command: cd /tmp && sudo wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz && sudo tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz && sudo cp -R cmake-3.3.2-Linux-x86_64/bin /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/doc /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/man /usr/ && sudo cp -R cmake-3.3.2-Linux-x86_64/share /usr/

      - run:
          name: install dependencies
          command: sudo pip install -e '.[develop]'

      - run:
          name: run tests
          command: py.test --cov=genomelake tests/

      - run:
          name: run coveralls
          command: coveralls || true

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2

  # TODO - consider running the deploy only on
  # tag commits: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
  test-n-deploy:
    jobs:
      - test-py35
      - test-py27
